// Address all the TODOs to make the tests pass!

// I AM NOT DONE
struct ColorStruct { // TODO: Something goes here
// TODO: Your struct needs to have red, green, blue fields
}


#[test]
fn classic_c_structs() {
    // TODO: Instantiate a classic color struct!
    // Green color neeeds to have green set to 255 and, red and blue, set to 0
    // let green =
    assert(green.red == 0);
    assert(green.green == 255);
    assert(green.blue == 0);
}
