// Integer types implement basic comparison and arithmetic operators.

// I AM NOT DONE

// TODO
// Return the solution of x^3 + y - 2

fn poly(x: u32, y: u32) -> u32 {
    // FILL ME
    res // Do not change
}


// Do not change the test function
#[test]
fn test_poly() {
    let res = poly(5, 3);

    assert(res == 126);
    assert(res < 300);
    assert(res <= 300);
    assert(res > 20);
    assert(res >= 2);
    assert(res != 27);
    assert(res % 2 == 0);
}

